using System; using System.Collections.Generic; using System.Linq; using System.Text; using System.Threading.Tasks; /*  * 2. Registrant Holds the following information: a. registration number – identification number for a registrant b. name – a registrant’s name c. date of birth d. address – address of the registrant (use structs) e. telephone number – 10-digit phone number  */ namespace ClubLib {     [Serializable]     public class Registrant     {          private int registrationNumber = 0;         //public static int counter = 0;         private string name;         private DateTime dateOfBirth;         private Address address;         private ulong phoneNumber;         Club club;         int numOfRegistrants;          public int RegistrationNumber         {             //set {  registrationNumber = value; }             get { return registrationNumber; }         }         public string Name         {             set { name = value;}             get { return name; }         }         public DateTime DateOfBirth         {             set {  dateOfBirth = value; }             get {  return dateOfBirth;}         }         public Address Address         {             set { address = value; }             get { return address; }         }          public ulong PhoneNumber         {             set             { phoneNumber = value; }             get             { return phoneNumber; }         } 
        public Club Club         {             get { return club; }             set
            {                 if (club == null)
                {                     club = value;                     if (club.Registrants[numOfRegistrants++].RegistrationNumber != RegistrationNumber)
                    {                         club.Registrants[numOfRegistrants] = this;                     }                 }                 else
                {                     throw new Exception("Swimmer is registered with a different club " + club.Name);                 }             }         }         public Registrant()         {             registrationNumber = RegNoGenerator.GetRegNo();         }         public Registrant(string name, DateTime dateOfBirth, Address address, ulong phoneNumber):this()         {             Name = name;             DateOfBirth = dateOfBirth;             Address = address;             PhoneNumber = phoneNumber;         }
        public Registrant(int regNo,string name, DateTime dateOfBirth, Address address, ulong phoneNumber)         {             registrationNumber = regNo;             Name = name;             DateOfBirth = dateOfBirth;             Address = address;             PhoneNumber = phoneNumber;         }
        public override string ToString()
        {  
            string info = "";
            info += string.Format("Name: {0} \nAddress: \n\t{1} \n\t{2} \n\t{3} \n\t{4} \nPhone: {5} \nDOB: {6} \nReg number: {7} \nClub: {8}", Name, address.Street, address.City, address.Province, address.Zip, PhoneNumber, DateOfBirth, registrationNumber, Club == null ? "not assigned" : Club.Name);
            return info;
        }
    } } 